export default {}
export const BOOK_LIST_GET = 'BOOK_LIST_GET'
export const BOOK_LIST_POST = 'BOOK_LIST_POST'
export const BOOK_LIST_DELETE = 'BOOK_LIST_DELETE'
export const BOOK_LIST_PUT = 'BOOK_LIST_PUT'

export const CATALOGS_GET = 'CATALOGS_GET'
export const CATALOGS_POST = 'CATALOGS_POST'
export const CATALOGS_DELETE = 'CATALOGS_DELETE'
export const CATALOGS_PUT = 'CATALOGS_PUT'

export const SCHEMA_LIST_GET = 'SCHEMA_LIST_GET'
export const SCHEMA_DETAIL_GET = 'SCHEMA_DETAIL_GET'
export const SCHEMA_DELETE = 'SCHEMA_DELETE'
export const SCHEMA_POST = 'SCHEMA_POST'
export const SCHEMA_PUT = 'SCHEMA_PUT'
export const SCHEMA_FIELD_POST = 'SCHEMA_FIELD_POST'
export const SCHEMA_FIELD_PUT = 'SCHEMA_FIELD_PUT'
export const SCHEMA_FIELD_DELETE = 'SCHEMA_FIELD_DELETE'

export const ARTICLE_LIST_GET = 'ARTICLE_LIST_GET'
export const ARTICLE_RECENTLY_LIST_GET = 'ARTICLE_RECENTLY_LIST_GET'
export const ARTICLE_DES_GET = 'ARTICLE_DES_GET'
export const ARTICLE_CUR_SAVE = 'ARTICLE_CUR_SAVE'
export const ARTICLE_POST = 'ARTICLE_POST'
export const ARTICLE_PUT = 'ARTICLE_PUT'
export const ARTICLE_DELETE = 'ARTICLE_DELETE'
export const ARTICLE_CONTENT_PUT = 'ARTICLE_CONTENT_PUT'
export const ARTICLE_CONTENT_POST = 'ARTICLE_CONTENT_POST'
export const ARTICLE_CONTENT_DELETE = 'ARTICLE_CONTENT_DELETE'


export const LOGIN_POST = 'LOGIN_POST'
export const USER_POST = 'USER_POST'
