export const BOOK_LIST_SAVE = 'BOOK_LIST_SAVE'
export const BOOK_LIST_UPDATE = 'BOOK_LIST_UPDATE'
export const BOOK_CUR_UPDATE = 'BOOK_CUR_UPDATE'

export const CATALOGS_SAVE = 'CATALOGS_SAVE'
export const CATALOGS_CUR_SAVE = 'CATALOGS_CUR_SAVE'
export const CATALOGS_TEMPLATE_CREATE = 'CATALOGS_TEMPLATE_CREATE'
export const CATALOGS_OPEN_TOGGLE = 'CATALOGS_OPEN_TOGGLE'
export const CATALOGS_OPEN_RESET = 'CATALOGS_OPEN_RESET'

// schema

export const SCHEMA_LIST_SAVE = 'SCHEMA_LIST_SAVE'
export const SCHEMA_LIST_UPDATE = 'SCHEMA_LIST_UPDATE'
export const SCHEMA_CUR_SAVE = 'SCHEMA_CUR_SAVE'

export const ARTICLE_LIST_SAVE = 'ARTICLE_LIST_SAVE'
export const ARTICLE_DES_SAVE = 'ARTICLE_DES_SAVE'
export const ARTICLE_CUS_SAVE = 'ARTICLE_CUS_SAVE'

export const USER_SAVE = 'USER_SAVE'
export const ISVISITOR_SAVE = 'ISVISITOR_SAVE'
export const CUR_USER_INFO_SAVE = 'CUR_USER_INFO_SAVE'
export const CUR_USER_LAYOUT_SAVE = 'CUR_USER_LAYOUT_SAVE'

// notes

export const NOTE_LIST_SAVE = 'NOTE_LIST_SAVE'
export const NOTE_LIST_UPDATE = 'NOTE_LIST_UPDATE'
export const NOTE_CUR_UPDATE = 'NOTE_CUR_UPDATE'
export const NOTE_MAP_SAVE = 'NOTE_MAP_SAVE'
export const NOTE_CUR_CONTENT_UPDATE = 'NOTE_CUR_CONTENT_UPDATE'

// config

export const CONFIG_TOGGLE_SAVE = 'CONFIG_TOGGLE_SAVE'
